#Integer; The number of times it publishes Geofence Acknowledgement.
ack_pub_times: 1 
#Double; Max lane width in meters within which geofence points are associated to a lanelet as those points are guaranteed to apply to a single lane
max_lane_width: 4.0

#Double: Period in seconds between traffic control requests after route selection
traffic_control_request_period: 3.0

#List of Int: Every element corresponds to intersection_id of every two elements (x,y) in intersection_coord_correction (id must be [0, +65535] ranges)
intersection_ids_for_correction: [9945, 9001]

#List of Double: Every 2 element describes coordinate correction [delta_x, delta_y] for each intersection_id in intersection_ids_for_correction in same order
intersection_coord_correction: [0.0, -1.5, -0.5, -1.0]

#List of Int: Route lanelets for external object route (if empty, no external object is published)
#external_object_route_coords: [-66.980, 322.7323, -65.0987, 333.5559, -45.0, 300.0]
external_object_route_coords: [215.279, 242.601, 218.969, 252.677]

#Double: Speed of the external object's speed in m/s
external_object_speed: 1.0

#Double: Seconds between start and end of the simulation to repeat
external_object_spawn_delay_period: 4.0