timeHeadway: 3.5 
standStillHeadway: 22.0
maxAccel: 1.0 
Kp: 0.15 
Kd: 0.05 
Ki: 0.0 
maxValue: 2.0
minValue: -10.0
cmdTmestamp: 100
adjustmentCap: 2.0 
dt: 0.1
integratorMax: 100
integratorMin: -100
wheelBase: 2.7
lowpassGain: 1.0
lookaheadRatio: 2.0 
minLookaheadDist: 6.0 